{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abi.secretName" . }}
  labels:
    {{- include "abi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  ABI_OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ABI_ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.huggingfaceToken }}
  ABI_HF_API_TOKEN: {{ .Values.secrets.huggingfaceToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.discordBotToken }}
  DISCORD_BOT_TOKEN: {{ .Values.secrets.discordBotToken | b64enc | quote }}
  {{- end }}
{{- end }}
